### PR TITLE
autoreload default is false - fix this when no ENV is set

### PR DESCRIPTION
**Pull request by janwo**
Default should be false as described in README.md

Please fix :)

### CODE REVIEW

**Comment by niftylettuce** [comment]
Ah nah we should update the README instead I think

**Comment by janwo** [comment]
I would recommend to set it to false, because...
- Watching files seems to be more a feature used in development, doesn't it?
- Jest testing framework throws a warning as the file watch mode keeps a thread running. I had to debug a while until I realized, that this package caused this issue.

**Comment by niftylettuce** [comment]
A step further would be to make it off in non-development env, would you agree? Or just make it false always

**Comment by janwo** [comment]
What about setting this to true in dev/development environment, otherwise false (default)?

**Comment by janwo** [comment]
@niftylettuce Quick info: Its also stated in the documentation of i18n 0.13.2 that `autoreload` is false by default.

**Comment by niftylettuce** [comment]
v7.0.0 released with this fix, thank you @janwo 

https://github.com/ladjs/i18n/releases/tag/v7.0.0

**Pull request merged**
