### PR TITLE
Implement custom locale detection using a new 'detectLocale' parameter

### PR DESCRIPTION
**Pull request by nemphys**

### CODE REVIEW

**Comment by niftylettuce** [comment]
In README update you have "localeDetection parameter", but this should be "\`detectLocale\` parameter" with backticks surrounding it if possible as similar to others.  Also, please set the default to `false` instead of `null`, and also add a few tests if you can?

**Comment by nemphys** [comment]
Fixed (sorry, in the beginning the parameter name was different and forgot to update it).
What kind of tests would you like?

**Comment by niftylettuce** [comment]
Just something simple so code coverage hits it :)

**Comment by nemphys** [comment]
Hmm, not very helpful :-) but I'll think of something as soon as I find the time.

**Comment by niftylettuce** [comment]
I can write the test no worries

**Comment by niftylettuce** [comment]
v7.1.0 released https://github.com/ladjs/i18n/releases/tag/v7.1.0 @nemphys

**Comment by niftylettuce** [comment]
here's what I was thinking of for the test https://github.com/ladjs/i18n/commit/5e4121ecc8f0086cc71a4fb1c1e376c1fb87085b#diff-a561630bb56b82342bc66697aee2ad96efddcbc9d150665abd6fb7ecb7c0ab2f

**Comment by nemphys** [comment]
Cool, thanx!

**Pull request merged**
